// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Int = require("rescript/lib/js/belt_Int.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Caml_array = require("rescript/lib/js/caml_array.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");

var inputs = Belt_Array.map(Belt_Array.map(Fs.readFileSync("./input.txt", "utf8").split("\n"), Belt_Int.fromString), Belt_Option.getExn);

var largerValues = Belt_Array.reduceWithIndex(inputs, 0, (function (sum, value, index) {
        if (index === 0) {
          return sum;
        }
        var previousValue = Caml_array.get(inputs, index - 1 | 0);
        var toAdd = value > previousValue ? 1 : 0;
        return sum + toAdd | 0;
      }));

console.log(largerValues);

exports.inputs = inputs;
exports.largerValues = largerValues;
/* inputs Not a pure module */
